name: open-source-hooks

on:
  push:
    branches:
      - "test-and-cicd"

jobs:
  test:
    name: "Node ${{ matrix.node }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - run: yarn test:ci
